### ISSUE TITLE
External Drive/USB Install

### ISSUE THREAD

**Issue by iamwagz** [danerieber/mubi-gui#1]
Hi, does this work with an external drive? Are there any requirements for file system or does the partition tool take care of this? I'm looking to install and run Ubuntu as an "app" from an external drive, possible?

**Comment by danerieber** [comment]
Hey I'm really sorry but this is a project that I didn't complete and I forgot to pull off of GitHub. I can finish it if you want, though. It might take some time since I'm busy right now. And about running Ubuntu from an external drive, yes it's totally possible and you can even run it off a flash drive! If you want me to complete the app then I'll make sure it's automated for the most part so it's not difficult to use. You can try my command-line version, mubi, even though it's more difficult to use. Just check out my other projects and you'll find it. Also, mubi might not be updated to use the lstest version of Ubuntu.

**Comment by danerieber** [comment]
Another update: The command-line version of mubi is obsolete now. The link for the Ubuntu disk image is an old one that doesn't work now.

**Comment by iamwagz** [comment]
Thanks for getting back to me. I don't expect you to finish the project just for me, if you've moved on that's ok as I don't have time myself to develop it - but thanks for offering! I have found your other project without the GUI, I'm assuming you created this because the work on the "Mac version of Wubi" was never completed? I've seen installations of Ubuntu in Wubi running inside Windows "as an app", but never on a Mac. I have a specific need for running a Ubuntu packaged software suite that I only want to dabble in without needing to partition my drive etc., would you be able to point me in the right direction for doing this on a Mac?

**Comment by danerieber** [comment]
Well I should probably finish it anyways (and yes it's like wubi but for mac), but in the meantime you can follow this tutorial to create a bootable drive: http://www.ubuntu.com/download/desktop/create-a-usb-stick-on-mac-osx. It says USB stick but I'm 99% positive it will work with an external drive. I've followed this many times, even for other Linux distributions, and it has never failed me. If you have any troubles following it just let me know. Enjoy your portable Ubuntu!

P.S. So you can partition your internal drive to make space for Ubuntu if you want to run it off of a USB, but if you have a large enough external drive, the Live CD will work just fine with the space it has. I know it can be tricky and sometimes dangerous to partition drives!

**Comment by danerieber** [comment]
I'll be glad to help more tomorrow if you need it. I'm done for the night (it's night here, don't know about you).

**Comment by iamwagz** [comment]
Thank you so much for all of the information. I've found that link before and was going to be my next step anyway, I'm versed in partitioning and running portable apps on external drives - I must admit I was just trying to find a more streamlined solution for this one (that's how your app popped up). 

Again, thanks for your help, much appreciated! I'll stay tuned on this one if you make any developments.

**Comment by danerieber** [comment]
No problem :+1:
